blog/blog/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'blog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^blog/', include('post.urls', namespace='post')),
    url(r'^admin/', include(admin.site.urls)),
)

blog/post/urls.py
from django.conf.urls import patterns, url
from views import PostListing, PostCreate, PostDetail, PostUpdate, PostDelete


urlpatterns = patterns('post',
    url(r'^$', PostListing.as_view(), name='listing'),
    url(r'^create/$', PostCreate.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', PostDetail.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/update/$', PostUpdate.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/delete/$', PostDelete.as_view(), name='delete'),
)

my_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('post.urls', namespace='post')),
]

post/urls.py
from django.conf.urls import patterns, url

from .views import PostListView, PostCreateView, PostDetailView, \
    PostUpdateView, PostDeleteView


urlpatterns = [
    url(r'^$', PostListView.as_view(), name='list'),
    url(r'^create/$', PostCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', PostDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/update/$', PostUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/delete/$', PostDeleteView.as_view(), name='delete'),
]

blog/post/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()

    def __unicode__(self):
        return self.title

post/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()

    def __str__(self):
        return self.title

blog/post/views.py
from django.views.generic import ListView, CreateView, DetailView, UpdateView, \
    DeleteView
from django.core.urlresolvers import reverse, reverse_lazy
from models import Post


# Create your views here.

class PostListing(ListView):
    model = Post
    template_name = 'post/index.html'
    # content_object_name = 'object_list'
    paginate_by = 2


class PostCreate(CreateView):
    model = Post
    fields = ['title', 'body']
    template_name = 'post/new.html'
    success_url = reverse_lazy('post:listing')


class PostDetail(DetailView):
    model = Post
    template_name = 'post/detail.html'


class PostUpdate(UpdateView):
    model = Post
    fields = ['title', 'body']
    template_name = 'post/edit.html'

    def get_success_url(self):
        return reverse(
            'post:detail',
            kwargs={
                'pk': self.object.pk,
            }
        )


class PostDelete(DeleteView):
    model = Post
    template_name = 'post/delete.html'
    success_url = reverse_lazy('post:listing')

post/views.py
from django.views.generic import ListView, CreateView, DetailView, UpdateView,\
    DeleteView
from django.core.urlresolvers import reverse, reverse_lazy

from .models import Post

# Create your views here.


class PostListView(ListView):
    model = Post
    paginate_by = 2


class PostCreateView(CreateView):
    model = Post
    fields = ['title', 'body']
    success_url = reverse_lazy('post:list')


class PostDetailView(DetailView):
    model = Post


class PostUpdateView(UpdateView):
    model = Post
    fields = ['title', 'body']

    def get_success_url(self):
        return reverse(
            'post:detail',
            kwargs={
                'pk': self.object.pk,
            }
        )


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('post:list')

blog/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>
        {% block title %} {% endblock %}
    </title>
</head>
<body>
<h1>
    {% block app %} {% endblock %}
</h1>
{% block menu %} {% endblock %}
<hr/>
    {% block content %} {% endblock %}
</body>
</html>

blog/templates/post/delete.html
{% extends 'base.html' %}

{% block title %}
    Post CRUD
{% endblock %}

{% block app %}
    Post CRUD Delete
{% endblock %}

{% block menu %}
    {% include 'post/menu.html' %}
{%  endblock %}

{% block content %}


    <form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Delete">
    </form>

{% endblock %}

blog/templates/post/detail.html
{% extends 'base.html' %}

{% block title %}
    Post CRUD
{% endblock %}

{% block app %}
    Post CRUD Detail
{% endblock %}

{% block menu %}
    {% include 'post/menu.html' %}
{%  endblock %}

{% block content %}

    <h1> {{ post.title }} </h1>
    <p> {{ post.body }} </p>

    <a href="{% url "post:update" post.pk %}">Edit</a>
    <a href="{% url "post:delete" post.pk %}">Delete</a>
{% endblock %}

blog/templates/post/edit.html
{% extends 'base.html' %}

{% block title %}
    Post CRUD
{% endblock %}

{% block app %}
    Post CRUD Edit
{% endblock %}

{% block menu %}
    {% include 'post/menu.html' %}
{%  endblock %}

{% block content %}

    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Edit">
    </form>

{% endblock %}

blog/templates/post/index.html
{% extends 'base.html' %}

{% block title %}
    Post CRUD
{% endblock %}

{% block app %}
    Post CRUD example
{% endblock %}

{% block menu %}
    {% include 'post/menu.html' %}
{%  endblock %}

{% block content %}

    <ul>
        {% for post in post_list %}
            <li>
                <a href='{% url "post:detail" post.pk %}'>
                {{ post.title }}
                <a>
            </li>
        {% endfor %}
    </ul>
    <br/>

    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a href="{% url 'post:listing' %}?page={{ page_obj.previous_page_number }}">anterior</a>
        {% endif %}
        Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
            <a href="{% url 'post:listing' %}?page={{ page_obj.next_page_number }}">siguiente</a>
        {% endif %}
    {% endif %}

{% endblock %}

blog/templates/post/menu.html
<a href="{% url 'post:listing' %}">Home</a> |
<a href="{% url 'post:create' %}">Create</a> |

blog/templates/post/new.html
{% extends 'base.html' %}

{% block title %}
    Post CRUD
{% endblock %}

{% block app %}
    Post CRUD New
{% endblock %}

{% block menu %}
    {% include 'post/menu.html' %}
{%  endblock %}

{% block content %}

    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
    </form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>
        {% block title %} {% endblock %}
    </title>
</head>
<body>
<h1>
    {% block app %} {% endblock %}
</h1>
{% block menu %} {% endblock %}
<hr/>
    {% block content %} {% endblock %}
</body>
</html>

templates/menu.html
<a href="{% url 'post:list' %}">Home</a> |
<a href="{% url 'post:create' %}">Create</a> 

templates/post/post_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    Post CRUD
{% endblock %}

{% block app %}
    Post CRUD Delete
{% endblock %}

{% block menu %}
    {% include 'menu.html' %}
{%  endblock %}

{% block content %}


    <form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ post }}"?</p>
    <input type="submit" value="Delete">
    </form>

{% endblock %}

templates/post/post_detail.html
{% extends 'base.html' %}

{% block title %}
    Post CRUD
{% endblock %}

{% block app %}
    Post CRUD Detail
{% endblock %}

{% block menu %}
    {% include 'menu.html' %}
{%  endblock %}

{% block content %}

    <h1> {{ post.title }} </h1>
    <p> {{ post.body }} </p>

    <a href="{% url "post:update" post.pk %}">Edit</a>
    <a href="{% url "post:delete" post.pk %}">Delete</a>
{% endblock %}

templates/post/post_form.html
{% extends 'base.html' %}

{% block title %}
    Post CRUD
{% endblock %}

{% block app %}
    Post CRUD New
{% endblock %}

{% block menu %}
    {% include 'menu.html' %}
{%  endblock %}

{% block content %}

    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
    </form>

{% endblock %}

templates/post/post_list.html
{% extends 'base.html' %}

{% block title %}
    Post CRUD
{% endblock %}

{% block app %}
    Post CRUD example
{% endblock %}

{% block menu %}
    {% include 'menu.html' %}
{%  endblock %}

{% block content %}

    <ul>
        {% for post in post_list %}
            <li>
                <a href='{% url "post:detail" post.pk %}'>
                {{ post.title }}
                <a>
            </li>
        {% endfor %}
    </ul>
    <br/>

    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a href="{% url 'post:list' %}?page={{ page_obj.previous_page_number }}">before</a>
        {% endif %}
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
            <a href="{% url 'post:list' %}?page={{ page_obj.next_page_number }}">next</a>
        {% endif %}
    {% endif %}

{% endblock %}